/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzq_jni_model_JniAndHeaderFile */

#ifndef _Included_com_zzq_jni_model_JniAndHeaderFile
#define _Included_com_zzq_jni_model_JniAndHeaderFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzq_jni_model_JniAndHeaderFile
 * Method:    fromJniAndHeaderFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzq_jni_model_JniAndHeaderFile_fromJniAndHeaderFile
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
